enum
{
    INVALID_DIALOG_ID,
    DIALOG_DIARY_MAIN,
    DIALOG_DIARY_CONTROL_OF_RECORDS,
    DIALOG_INFORMATION_ABOUT_RECORD,
    DIALOG_DONATE_MAIN,
    DIALOG_DONATE_BUY_ADMIN,
    DIALOG_BLACK_MARKET_PRODUCTS,
    DIALOG_BUY_BLACK_MARKET_WEAPON,
    DIALOG_BUY_BLACK_MARKET_DRUGS,
    DIALOG_BUY_BLACK_MARKET_KEYS
}

enum 
{
    DIALOG_RESPONSE_TYPE_OK = 1,
    DIALOG_RESPONSE_TYPE_NOT = 0
}