enum 
{
    DIARY_SHOW_TYPE_MAIN,
    // DIARY_SHOW_TYPE_CONTROL_OF_RECORDS
    DIARY_SHOW_TYPE_CONTROL_OF_RECO,
    // DIARY_SHOW_TYPE_COUNT_OF_RECORDS
    DIARY_SHOW_TYPE_COUNT_OF_RECORD
}

enum 
{
    DIARY_CONTROL_TYPE_NEXT_PAGE,
    // DIARY_CONTROL_TYPE_PREVIOUS_PAGE
    DIARY_CONTROL_TYPE_PREVIOUS_PAG
}