enum
{
    DONATE_SHOW_TYPE_MAIN,
    DONATE_SHOW_TYPE_BUY_ADMIN,
    DONATE_SHOW_TYPE_BUY_LEADER,
    DONATE_SHOW_TYPE_BUY_DONAT_AUTO
}

enum 
{
    ADMIN_LVL_MODERATOR_PRICE = 50,
    ADMIN_LVL_MODERATOR_SEC_PRICE = 100,
    ADMIN_LVL_MODERATOR_THREE_PRICE = 150,
    // ADMIN_LVL_MODERATOR_FOURTH_PRICE
    ADMIN_LVL_MODERATOR_FOURTH_PRIC = 200,
    ADMIN_LVL_MODERATOR_FIVE_PRICE = 250,
    ADMIN_LVL_MODERATOR_SIXTH_PRICE = 300,
    ADMIN_LVL_MODERATOR_SEVEN_PRICE = 350,
    ADMIN_LVL_GRANDMODERATOR_PRICE = 400,
    ADMIN_LVL_DEPUTY_PRICE = 1000,
    ADMIN_LVL_FOUNDER_PRICE = 2000
}