enum 
{
    ADMIN_LVL_TYPE_MODERATOR = 1,
    ADMIN_LVL_TYPE_MODERATOR_SEC,
    ADMIN_LVL_TYPE_MODERATOR_THREE,
    ADMIN_LVL_TYPE_MODERATOR_FOURTH,
    ADMIN_LVL_TYPE_MODERATOR_FIVE,
    ADMIN_LVL_TYPE_MODERATOR_SIXTH,
    ADMIN_LVL_TYPE_MODERATOR_SEVEN,
    ADMIN_LVL_TYPE_GRANDMODERATOR,
    ADMIN_LVL_TYPE_DEPUTY,
    ADMIN_LVL_TYPE_FOUNDER
}

enum 
{
    ADMIN_TYPE_REAL,
    ADMIN_TYPE_PURCHASED
}